"""empty message

Revision ID: 35d805a9a8e7
Revises: 
Create Date: 2022-10-10 14:03:32.061023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35d805a9a8e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('doors', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('people')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pname', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('color', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='people_pkey'),
    sa.UniqueConstraint('pname', name='people_pname_key')
    )
    op.drop_table('cars')
    # ### end Alembic commands ###
